services:
  php:
    container_name: php
    build: ./docker/php/
    volumes:
      - ./laravel:/var/www/html
    networks:
      - docker-laravel
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
    ports:
      - 80:80    # For Nginx or Apache
      - 5173:5173

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - docker-laravel
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf/conf.d:/etc/nginx/conf.d
  
  pgsql:
    container_name: pgsql
    image: postgres:latest
    networks:
      - docker-laravel
    environment:
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./my-db:/var/lib/postgresql/data

networks:
 docker-laravel:
  driver: bridge

volumes:
  my-db:
  laravel:
